server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions: 
  filename: /tmp/positions.yaml

clients: 
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # This scrapes logs from Docker containers
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Only collect logs from containers with the label "logging=promtail"
      - source_labels: ['__meta_docker_container_label_logging']
        regex: promtail
        action: keep
      # Add container name as a label
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      # Parse JSON logs
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'