server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions: 
  filename: /tmp/positions.yaml

clients: 
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # This scrapes logs from Docker containers
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Add container name as a label
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)' 
        target_label: 'container'
      # Use container name for job if logging_jobname label exists, otherwise use container name  
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        regex: '(.+)'
        target_label: 'job'
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'job'
        action: replace